name: Meu primeiro Workflow no Github Actions

on:
  push:
    branches: [ "main" ]

jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: self-hosted   
    steps:
      - name: Step 1
      - uses: actions/checkout@v3      
        run: echo Ol치, turma da disciplina Github Actions!
        
      - name: Step 2
        run: echo "Ol치, turma da disciplina Github Actions! step 2"
        
      - name: Step 3
        run: echo "Ol치, turma da disciplina Github Actions! step 3"
        
      - name: Step 4
        run: echo "Ol치, turma da disciplina Github Actions! step 4"
